### ISSUE TITLE
Program having issues finding the correct files

### ISSUE THREAD

**Issue by jamesyitan** [dyxstat/MetaCC#1]
Hi Yuxuan! Thanks for making this program. It runs much better than HiCBin for sure.

These seem like relatively minor issues, but figured that they be brought up at least.

When I run the program from outside the MetaCC directory, it seems like the program has a hard time finding the program files. This is easily solved by cd'ing into the MetaCC directory and then running the program. That's not so much a big deal.

A slightly more problematic issue is when I try running:
```bash
python MetaCC.py postprocess --cover -v \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/samples/samp_508/assembly/megahit_noNORM/final.contigs.renamed.fa \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508/contaminated_bins.csv \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508
```
after I've run checkM and also have all the correct files for the postprocessing steps.

It gives me the error: "File NormCC_normalized_contact.gz is not found", even though I've checked and the file is certainly in the designated output directory from my first pass through MetaCC.

Let me know if that makes sense or not.

**Comment by dyxstat** [comment]
Hi James,

Thanks for your feedback! Can you check whether the file '/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508/NormCC_normalized_contact.gz' exists? 

Moreover, can you provide me with all the commands you use for MetaCC and the list of the file names under the directory '/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508'?

Best,
Yuxuan

**Comment by jamesyitan** [comment]
Here is what is in '/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508':

![image](https://github.com/dyxstat/MetaCC/assets/25512418/e93da32f-29b9-41aa-86e9-1aeb9df1b7a5)

"NormCC_normalized_contact.gz" is certainly in there.

Here are the commands I used for MetaCC:
```bash
python MetaCC.py norm -e Sau3AI -e MluCI --cover -v \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/samples/samp_508/assembly/megahit_noNORM/final.contigs.renamed.fa \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/erie_hic/MAP_samp_508_SORTED.bam \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508

python MetaCC.py bin --cover -v \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/samples/samp_508/assembly/megahit_noNORM/final.contigs.renamed.fa \
/scratch/duhaimem_root/duhaimem1/jamestan/from_turbo_20230822/metacc/samp_508
```

**Comment by dyxstat** [comment]
Hi James,

It's very wired since the 'bin' module can find the 'NormCC_normalized_contact.gz' file but the 'postprocess' module cannot. In fact, I write exactly the same codes for detecting this file in these two modules.

Can you provide me with the 'MetaCC.log' file so I may find out what happened here?

Yuxuan

**Comment by dyxstat** [comment]
Hi James,

It's very weird since the 'bin' module can find the 'NormCC_normalized_contact.gz' file but the 'postprocess' module cannot. In fact, I write exactly the same codes for detecting this file in these two modules.

Can you provide me with the 'MetaCC.log' file so I may find out what happened here?

Yuxuan

**Comment by jamesyitan** [comment]
Oh sorry, Yuxuan!

There was some weird indexing in my bash script. After I looked at the log file, I realized the file names were just slightly wrong.

I think I should be okay now. I will let you know if something comes up again.
