### ISSUE TITLE
NormCC fails during glm fitting

### ISSUE THREAD

**Issue by bnelsj** [dyxstat/MetaCC#4]
Hi, I've found that the normalization step sometimes fails in normcc.R, where the glm fitter encounters NaN / Infinite values:
`Error in glm.fitter(x = X, y = Y, w = w, etastart = eta, offset = offset,  : 
  NA/NaN/Inf in 'x'`
  A test dataset is attached.
[contig_info.csv](https://github.com/dyxstat/MetaCC/files/14499203/contig_info.csv)

I was able to resolve this issue by using python statsmodels for the glm fitting, but I don't know if that would be satisfactory here.

**Comment by dyxstat** [comment]
Hi,

Thanks for trying our method. 

Could you let me know the specific functions and commands you use for Python statsmodels?

Best

**Comment by bnelsj** [comment]
Hi,

Here's a snippet that takes a contig_info.csv file and returns the list of fitted parameters:
```
import numpy as np
import pandas as pd
import statsmodels.api as sm

def normcc(contig_file):
    names = ['contig_name', 'site', 'length', 'covcc', 'signal']
    df = pd.read_csv(contig_file, header=None, names=names)
    df['sample_site'] = np.log(df['site'])
    df['sample_len'] = np.log(df['length'])
    df['sample_covcc'] = np.log(df['covcc'])
    exog = df[['sample_site', 'sample_len', 'sample_covcc']]
    endog = df[['signal']]
    exog = sm.add_constant(exog)
    glm_nb = sm.GLM(endog, exog, family=sm.families.NegativeBinomial(alpha=1))
    res = glm_nb.fit(method="lbfgs")
    norm_result = res.params.to_list()
    return norm_result
```

I can also put in a PR if that would be helpful.

**Comment by dyxstat** [comment]
Hi,

Sorry, I'm late getting back to you. I've been really busy looking for a job lately.

I checked the results from your Python function against NormCC's R script on three different datasets. They look close enough, so I think it's fine to use your Python function.

Thanks again for trying out our software.

Best

**Comment by dyxstat** [comment]
Now MetaCC does not rely on R scripts. 

Thanks for your suggestions!
